import localFont from "next/font/local";
import "./globals.css";
import Header from "./component/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const basePath = process.env.NEXT_PUBLIC_BASE_PATH || "";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [{ rel: 'icon', url: `${basePath}/icon/test.png` }]
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {/* または、こちらでも可 */}
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
